name: Release
on:
  push:
    tags:
      - '*'

permissions: {}

jobs:
  build:
    name: Build artifacts
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
      with:
        fetch-depth: 0  # Needed for hatch-vcs versioning
        persist-credentials: false
    - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548  # v6.1.0
      with:
        python-version: "3.14"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build
    - name: Build package
      run: python -m build
    - name: Upload artifacts
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f  # v6.0.0
      with:
        name: artifacts
        path: |
          dist/protobug-*.whl
          dist/protobug-*.tar.gz
        compression-level: 0

  publish_pypi:
    name: Publish to PyPI
    needs: [build]
    if: github.repository == 'yt-dlp/protobug'
    permissions:
      id-token: write  # Needed for PyPI trusted publishing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131  # v7.0.0
      with:
        path: dist
        name: artifacts
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e  # v1.13.0
      with:
        verbose: true

  release:
    name: Create GitHub release
    needs: [build, publish_pypi]
    if: always() && !failure() && !cancelled()
    permissions:
      contents: write  # Needed by gh to publish release to Github
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
      with:
        persist-credentials: false
    - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131  # v7.0.0
      with:
        path: dist
        name: artifacts
    - name: Create GitHub Release
      env:
        GH_TOKEN: ${{ github.token }}
        TAG: ${{ github.ref_name }}
      run: |
        gh release create "${TAG}" \
          --title "protobug v${TAG}" \
          --generate-notes \
          --verify-tag \
          dist/protobug-*.whl \
          dist/protobug-*.tar.gz
